spring:
  application:
    name: proposta-app
  datasource:
    url: jdbc:postgresql://localhost:5432/propostadb
    password: 123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
rabbitmq:
  propostapendente:
    exchange: proposta-pendente.ex